version: "3.9"
services:
  chainlit:   # "chainlit"を任意の名前に変更
    container_name: chainlit    # "chainlit"を任意の名前に変更
    build:
      context: ./chainlit
      dockerfile: Dockerfile
      target: prd
    tty: true
    ports:
      - "8000:8000"