version: "3.9"
services:
  chainlit-dev:
    container_name: chainlit-dev
    build:
      context: ../
      dockerfile: Dockerfile
      target: dev
    tty: true
    volumes:
      - ../:/workspace
